use_frameworks!

platform :ios, '12.0'

target 'DataTransferLayer_Example' do
  pod 'DataTransferLayer', :path => '../'

  target 'DataTransferLayer_Tests' do
    inherit! :search_paths

    
  end
end
